
name: webserver-markdown-to-bbcode

services:
  webserver-markdown-to-bbcode:
    image: nginx:alpine
    container_name: webserver-markdown-to-bbcode
    volumes:
      - ./src:/usr/share/nginx/html/site:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fsS", "localhost"]
      interval: 1m
      timeout: 5s
      retries: 3

networks:
  default:
    name: local
    external: true
